# Generated by Django 5.0.1 on 2024-01-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicareapi', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissionalsaude',
            name='enderecos_atendimento',
            field=models.ManyToManyField(blank=True, related_name='profissionais_atendimento', to='clinicareapi.endereco'),
        ),
    ]
