# Generated by Django 5.0.1 on 2024-01-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicareapi', '0003_alter_profissionalsaude_enderecos_atendimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='user',
            new_name='user_paciente',
        ),
        migrations.RenameField(
            model_name='profissionalsaude',
            old_name='user',
            new_name='user_profissional',
        ),
    ]
