# Generated by Django 5.0.1 on 2024-01-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicareapi', '0004_rename_user_paciente_user_paciente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user',
            new_name='user_custom',
        ),
    ]
