# Generated by Django 5.0.1 on 2024-01-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicareapi', '0005_rename_user_customuser_user_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14, unique=True),
        ),
    ]
