# Generated by Django 5.0.1 on 2024-03-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicareapi', '0007_alter_customuser_user_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default='Seu Bairro', max_length=255),
        ),
    ]
