# Generated by Django 5.0.1 on 2024-07-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicareapi', '0008_endereco_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default='', max_length=255),
        ),
    ]
